### PR TITLE
refactor: set branch launcher as default launcher

### PR DESCRIPTION
**Pull request by javierron**
Signed-off-by: Javier Ron <javierron90@gmail.com>

### CODE REVIEW

**Comment by monperrus** [comment]
ready for merge?

**Comment by javierron** [comment]
Not yet, I'm still working on moving most classes that depend on the legacy launcher to the branch launcher.

**Comment by monperrus** [comment]
per our discussion, we separate the email notification improvement and the maven changed file resolution bug in a separate PR.

**Comment by monperrus** [comment]
Green here, and I see that you removed the unrelated changes in #1203 

Merge?

**Comment by javierron** [comment]
@monperrus yes, it's ready now.

**Comment by monperrus** [comment]
Thanks @javierron

**Pull request merged**
