### PR TITLE
test: fix flaky tests

### PR DESCRIPTION
**Pull request by henry-lp**

### CODE REVIEW

**Comment by monperrus** [comment]
@henry-lp conflicts here. rebase or close? Thanks!

**Comment by henry-lp** [comment]
@monperrus I have rebased :) .

**Comment by monperrus** [comment]
Thanks LGTM. ready to merge? if yes, could you unwip?

**Comment by henry-lp** [comment]
Ready to merge. I have unwip.

**Comment by monperrus** [comment]
thanks @henry-lp

**Pull request merged**
