### PR TITLE
Create new R-Hero PR message

### PR DESCRIPTION
**Pull request by javierron**
A PR message template for R-Hero patches.

Links still need to be added. You can see a sample [here](https://github.com/javierron/failingProject/pull/4)

### CODE REVIEW

**Comment by monperrus** [comment]
cool, updated the text.

**Comment by monperrus** [comment]
TODO: add the actual links to feedback web service

**Comment by javierron** [comment]
@monperrus I believe this one is ready.

**Comment by monperrus** [comment]
Cool!

**Pull request merged**
