### PR TITLE
Feat: add first version of jenkins plugin

### PR DESCRIPTION
**Pull request by henry-lp**
issue (#469). Goal is to see if this can be deployed on sonatype. 

Next: Jenkins build step instead of post build step.

### CODE REVIEW

**Comment by monperrus** [comment]
made minor change, please pull

**Comment by monperrus** [comment]
Good, it's well compiled by Travis CI. Could you add a file `docs/repairnator-jenkins-plugin.md` with the following sections

* How to install the Jenkins plugin?
* How to use the Jenkins plugin? (with screenshots)
  * Default usage
  * Configuration options
* Architecture (how it works, only for developers)

**Comment by henry-lp** [comment]
@monperrus done and done :) .

**Comment by henry-lp** [comment]
Test passed . Merge ? :)

**Comment by henry-lp** [comment]
@monperrus The test passed , we can try merging this and see if any .hpi is deployed to Sonatype :)

**Comment by henry-lp** [comment]
Deployment failed due to unable to submit .hpi to sonatype staging server . I guess we have to try a manual or auto release to Github instead. :) . This need to be reverted  or I can make a new PR to remove the new module in the pom.

**Pull request merged**
