### PR TITLE
doc: fix typos in README.md

### PR DESCRIPTION
**Pull request by PoojaChandak**
grammatical/typo changes
Signed-off-by: poojachandak <poojachandak002@gmail.com>

### CODE REVIEW

**Comment by PoojaChandak** [comment]
@monperrus can you please check if this is fine? Thanks.

**Comment by monperrus** [comment]
Does not seem so, see https://accounts.eclipse.org/legal/eca/validation/52364

Do you accept the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)?

**Comment by PoojaChandak** [comment]
Yes, I accepted the agreement. Not sure what is wrong.

**Comment by monperrus** [comment]
Thanks a lot for your contribution @PoojaChandak

**Pull request merged**
