### PR TITLE
fix: add logging for SequencerRepair-ODS integration

### PR DESCRIPTION
**Pull request by javierron**
- Added: write an ODS summary to a file after classification.
- Added: support to store ODS summary and files when running the pipeline in docker mode.

Signed-off-by: Javier Ron <javierron90@gmail.com>

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks Javier, @martinezmatias would you review and merge?

**Comment by javierron** [comment]
Converted to draft until I fix the broken test.

**Comment by martinezmatias** [comment]
Hi @monperrus, yes, I will review this PR.

**Comment by javierron** [comment]
@martinezmatias @monperrus PR is ready.

CI failure in maven-repair module is unrelated.

**Comment by monperrus** [comment]
Thanks @javierron

**Pull request merged**
