### PR TITLE
Move default travis API to `travis-ci.com`

### LINKED ISSUE #1231: Make travis-ci.com default
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Information from https://travis-ci.org/. Date of access: 15/06/2021.

Since https://travis-ci.org/ has ceased, we should move the default to https://travis-ci.com/

### PR DESCRIPTION
**Pull request by andre15silva**
Fixes #1231

### CODE REVIEW

**Comment by andre15silva** [comment]
The remaining places where `travis-ci.org` is used are tests that are built on top of certain travis builds only available on `travis-ci.org`.

**Comment by monperrus** [comment]
Nice.

**Comment by andre15silva** [comment]
`travis-ci.com` isn't behaving as expected in https://travis-ci.com/github/repairnator/test-repairnator/requests

I'm trying to trigger https://travis-ci.org/surli/test-repairnator/builds/352395977 but in `travis-ci.com`. I'll try a bit later, in case it is just a temporary issue with travis.

Also, the build `564711868` is no longer available, and is used in an example in the README. That should also be replaced by another example.

**Comment by monperrus** [comment]
Thanks for the update.

I was able to get a "build request" working right now, see 
https://app.travis-ci.com/github/repairnator/test-repairnator/requests

**Comment by andre15silva** [comment]
> I was able to get a "build request" working right now, see [app.travis-ci.com/github/repairnator/test-repairnator/requests](https://app.travis-ci.com/github/repairnator/test-repairnator/requests)

Thanks! Docs updated.

The only thing missing now is to update the `repairnator/pipeline` docker image, so that the default there is also `travis-ci.com` and the examples from the docs actually work.

For that we need to deploy a new version with these changes, so I say we merge this first, deploy, and then build the new docker image.

**Comment by monperrus** [comment]
Very good. Merged, thanks @andre15silva.

Do you have push access on dockerhub?

**Comment by andre15silva** [comment]
`repairnator-core` and `repairnator-pipeline` snapshots deployed.

docker image has been built 

> Do you have push access on dockerhub?

Yes, I have pushed the new image tagged as `repairnator/pipeline:3.3` and `repairnator/pipeline:latest`

**Comment by monperrus** [comment]
Thanks.

**Pull request merged**
