### PR TITLE
Fault localization mode

### LINKED ISSUE #1029: new mode for fault-localization only
The objective is on commit, it should build, then invoke Gzoltar to list the lines of code which are suspicious ..

Any suggestions???

### LINKED ISSUE #1116: integrate new fault localization system flacoco in Astor/Repairnator
* [ ] nopol https://github.com/SpoonLabs/nopol/issues/216
* [x] https://github.com/SpoonLabs/astor/issues/314
* [x] Flacoco should support Junit5 test https://github.com/SpoonLabs/flacoco/issues/10

### PR DESCRIPTION
**Pull request by andre15silva**
Repairnator is now able to export fault localization results to a PR review. (See https://github.com/repairnator/failingProject/pull/6).

```bash
java -cp target/repairnator-pipeline-3.3-SNAPSHOT-jar-with-dependencies.jar fr.inria.spirals.repairnator.pipeline.Launcher --launcherMode FAULT_LOCALIZATION --faultLocalization --build 235987498 --ghOauth $GITHUB_TOKEN
```

Opening this draft PR to make sure CI is still working.

TODO:
- [x] Add options for configuring flacoco
- [x] Add tests
- [x] Add documentation

Closes #1116
Closes #1029

### CODE REVIEW

**Comment by monperrus** [comment]
oh super nice

**Comment by andre15silva** [comment]
CI is failing due to running out of memory.

I tried to increase it in the `Jenkinsfile`, but I think it needs to be changed in Jenkins too:

> Failure executing: POST at: https://10.30.0.1/api/v1/namespaces/repairnator/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "my-agent-pod-vttvg-k5bfb" is forbidden: [maximum memory usage per Pod is 8448Mi, but limit is 17448304640, maximum memory usage per Container is 8Gi, but limit is 16Gi].

@javierron do you know if this is possible?

**Comment by andre15silva** [comment]
Seems like we are limited by Eclipse (see https://wiki.eclipse.org/CBI#Additional_Resource_Packs) to 8GiB.

I'm trying to work my way around this limit.

**Comment by andre15silva** [comment]
So, the issue with the Sorald test is related to some dependency colision with flacoco.

Now that Sorald has priority over flacoco, it is green. The other way around, Sorald's test runs out of memory.

**Comment by andre15silva** [comment]
Ready for review

**Pull request merged**
