### PR TITLE
chore: align package folders and package declarations

### PR DESCRIPTION
**Pull request by henry-lp**

### CODE REVIEW

**Comment by henry-lp** [comment]
@SophieHYe @monperrus ready for review :) .

**Comment by monperrus** [comment]
Thanks, we need the opposite, all classes should be in `pipeline`

**Comment by henry-lp** [comment]
@monperrus, then this PR can be closed I think, because everything were already in the pipeline originally :) . WDYT ?

**Comment by monperrus** [comment]
Thanks a lot @henry-lp

**Pull request merged**
