### PR TITLE
WIP: Styler support

### PR DESCRIPTION
**Pull request by andre15silva**
Reference: https://github.com/eclipse/repairnator/issues/979

## Changelog
- Introduce GatherCheckstyleInformation pipeline step, and tests
- Introduce StylerRepair repair step, and tests
- Introduce StylerConfig config manager

## TODO
- Move test project and docker image to repairnator org
- Documentation
- end2end test (requires https://github.com/KTH/styler/issues/17)

### CODE REVIEW

**Comment by andre15silva** [comment]
I currently have a test project that has some violations, and trained the models to generate possible fixes. 

The proposed fixes don't fix any violation, nevermind the entire violation set, so https://github.com/KTH/styler/issues/17 is essential in finishing the end2end testing and integration with repairnator.

**Comment by monperrus** [comment]
@fermadeiral we will soon finish the integration of Styler in Repairnator. would you still have some local changes in Styler which are not pushed to master? Thanks!

**Comment by monperrus** [comment]
ping @fermadeiral @andre15silva what's the status here?

**Comment by fermadeiral** [comment]
@monperrus I've pushed all local changes I had in https://github.com/KTH/styler's master branch.

**Comment by andre15silva** [comment]
- [ ] Rebase and merge https://github.com/andre15silva/styler/tree/repairnator and https://github.com/KTH/styler/tree/master
- [ ] Rebase and adapt the code here
- [ ] Close https://github.com/KTH/styler/issues/17 and use the result here

Unfortunately, I don't see myself having the time to finish this very soon tho.
There is still some heavy work to be done in these 3 points, and I also need to revive what I was doing.

**Comment by fermadeiral** [comment]
@andre15silva, the 3rd point is on me, right?

I'm gonna get back here.

**Comment by andre15silva** [comment]
> @andre15silva, the 3rd point is on me, right?
> 
> I'm gonna get back here.

Yes! 

iirc, what was needed was a build which failed due to checkstyle violations + a styler model which is able of fixing all those violations (i.e. fixing the build)

**Comment by fermadeiral** [comment]
> what was needed was a build which failed due to checkstyle violations

Oh, that will be out of my reach. I don't have the information of build breakage due to Checkstyle violations, this is not part of the experiments made for the Styler paper. I thought that you just needed a model that fixes violations in a project.

**Comment by monperrus** [comment]
@andre15silva you're by far the most qualified for this task, so if you can save a few hours to get it done, that would be great.

@fermadeiral even though your knowledge of Repairnator may be rusted, I'm sure you can also do this successfully, and that's very valuable.

on my side, we don't have an amanuens to staff on Repairnator right now, unfortunately.

**Comment by monperrus** [comment]
@andre15silva @fermadeiral it seems we will not finish this one.

are you OK to close?

**Comment by andre15silva** [comment]
> @andre15silva @fermadeiral it seems we will not finish this one.
> 
> are you OK to close?

yes, ok from me

**Pull request closed without merging**
