### PR TITLE
docs: changing repairnator file used to run the example

### PR DESCRIPTION
**Pull request by gustavopinto**
If I just run ``java -cp $TOOLS_JAR:target/repairnator-pipeline*.jar [...]`` as is, I would receive the following error message:

```
Error: Could not find or load main class fr.inria.spirals.repairnator.pipeline.Launcher
```

Besides, ``mvn install -DskipTests`` creates two jar files (with and without dependencies). It should be clear which one users should use.

Signed-off-by: Gustavo Pinto mail@gustavopinto.org

### CODE REVIEW

**Comment by monperrus** [comment]
Great. Could you fill the online Eclipse form for license agreement?

**Comment by gustavopinto** [comment]
Done with ti.

**Comment by monperrus** [comment]
Seems that the  eclipsefdn/eca is not happy. Do you use the same email address in the commit (git identity) and on the eclipse website?

**Comment by gustavopinto** [comment]
Yes, they are the same (mail at my domain).  Does it take time to propagate or something?

Just in case:
- I filled this form: https://accounts.eclipse.org/user/eca
- I also added my GitHub account to my eclipse profile
- On the STATUS box on the top right of ECA website, there is a check mark in the "Eclipse Contributor Agreement" item

Any tips from here?

BTW: I hard coded repairnator version on the documentation because using  the '*' wildcard does not seem to work with ``java -cp``.

**Comment by gustavopinto** [comment]
The problem is that I have to sign every commit. I tried to change the commit history to include this info, but I ended up duplicating some commits. 

It may be better to close this PR and start over again? Sorry for the mess.

**Comment by monperrus** [comment]
> It may be better to close this PR and start over again?

The best is to squash, sign and push-force

**Comment by gustavopinto** [comment]
There was a merge conflict after my last push, and I solved the conflict using GitHub web interface. I ended up not signing this merge commit. Do you want me to squash again?

**Comment by monperrus** [comment]
Merging this one, thanks a lot, documentation PRs are much appreciated :-)

Hopefully, the ECA bot will be happy next time ^^

**Comment by gustavopinto** [comment]
Thanks for the guidance!

**Pull request merged**
