### PR TITLE
Fix: update pipeline K8s yamlfile

### PR DESCRIPTION
**Pull request by henry-lp**
@monperrus Hi Martin :) , the pipeline is now on our cluster . I ran it together with build rainer and manual injection into ActiveMQ and found some improvements to be made. 
Instead of `System.exit(-1)` , which crash our K8s pipeline, we can return a boolean instead. WDYT ? 

PS: K8s does provide an auto crash recovery but It's better we spend it on real crashes instead of the ones we can handle like this one.

### CODE REVIEW

**Comment by monperrus** [comment]
LGTM. @gluckzhang do you merge?

**Comment by henry-lp** [comment]
Hi :) , I believe @gluckzhang does not have merge access to this repo .

**Comment by gluckzhang** [comment]
> LGTM. @gluckzhang do you merge?

Hi @monperrus , sorry I missed the message. I don't have merge access to this repo.

**Comment by monperrus** [comment]
We'll fix that later. Thanks a lot for the PR!

**Pull request merged**
