### PR TITLE
feat: introduce class RunInspector4Maven

### PR DESCRIPTION
**Pull request by andre15silva**
- Introduces RunInspector4Maven
- Test for RunInspector4Maven

### CODE REVIEW

**Comment by andre15silva** [comment]
Had a little (unrelated) hitch. Should be ready.

Next one needs this one merged first.

**Comment by monperrus** [comment]
We're almost there:

- The rebase with master is not complete, we should not see addNextSteps in the diff
- Could you add some API Javadoc in RunInspector4Maven?

Thanks!

**Comment by andre15silva** [comment]
>     * The rebase with master is not complete, we should not see addNextSteps in the diff
Fixed.

>     * Could you add some API Javadoc in RunInspector4Maven?
Added. Could you check to see if it is ok?

**Comment by monperrus** [comment]
Good, thanks. I'll merge after CI.

**Comment by andre15silva** [comment]
Might be a good idea to abort the ongoing job and the one queued after that, to save some time, as we don't have parallel jobs yet.

**Comment by monperrus** [comment]
Thanks @andre15silva

**Pull request merged**
