### PR TITLE
fix: improves Sequencer

### PR DESCRIPTION
**Pull request by javierron**
Astor detection strategy 
 - suspicious lines limit
 - suspicious value threshold
Sequencer collector:
 - Add context size config
Inspector:
 - Add travis build ID to "_topush" path

Signed-off-by: Javier Ron <javierron90@gmail.com>

### CODE REVIEW

**Comment by javierron** [comment]
I modified the functionality of the SequencerCollector to store the raw files along with the diffs.

With these files available the Sequencer training tokenizer will be able to generate training pairs extracting either the Abstract Buggy Context or the Unified Diff Context. 

Also, by doing this we keep the single-line-changes collector decoupled from any kind of context Sequencer uses to train its models.

**Comment by monperrus** [comment]
Perfect. Any idea why CI fails?

**Comment by javierron** [comment]
> Perfect. Any idea why CI fails?

@monperrus Yes! Because of my bad programming :sweat_smile:, but errors should be fixed now. 

Pipeline tests seem to be consistently timing out, should I split them in more jobs? Perhaps in another PR?

**Comment by monperrus** [comment]
Thanks @javierron

**Comment by monperrus** [comment]
> should I split them in more jobs? Perhaps in another PR?

Yes! We love, atomic, baby PR!

**Pull request merged**
