### PR TITLE
chore: improve CI config

### LINKED ISSUE #1170: Install junit-plugin in Jenkins
https://github.com/jenkinsci/junit-plugin allows us to access test reports, which is a useful thing for quickly checking what the actual problem is without running the tests locally, and to get more information about non-reproducible errors.

### PR DESCRIPTION
**Pull request by andre15silva**
- Increase `maven-repair` timeout, as it now includes `repairnator-pipeline` as a dependency.
- Add MAVEN_OPTS do `run-with-core.sh` script.
- Activate https://github.com/jenkinsci/junit-plugin. Closes #1170

### CODE REVIEW

**Comment by monperrus** [comment]
Small and green, LGTM. But no new dependency in maven-repair.

**Comment by andre15silva** [comment]
> Small and green, LGTM. But no new dependency in maven-repair.

Well, it was green because I removed `${MAVEN_OPTS}` from the script. There's a test failing because of that I think.

The dependency will come in the `maven-repair` PR.

**Comment by monperrus** [comment]
Ack, updated description accordingly

**Comment by andre15silva** [comment]
> Ack, updated description accordingly

OK! What I meant by that was that the script now includes installing `repairnator-pipeline`.

**Comment by andre15silva** [comment]
I think there is something weird going on with some tests.

The 9394dff failed but 7cf6f5b passed, and they are exactly the same.

**Comment by monperrus** [comment]
> The 9394dff failed but 7cf6f5b passed, and they are exactly the same.

This suggest we have a flaky test. Is that for one single test?

**Comment by andre15silva** [comment]
Should be ready. Flaky test hasn't failed again.

**Comment by monperrus** [comment]
Nice, thanks @andre15silva.

We can now rebase the subsequent PRs and proceed.

**Pull request merged**
