### PR TITLE
chore: Jenkins plugin deployment failure fix

### PR DESCRIPTION
**Pull request by henry-lp**
issue (#469)  @monperrus 
Previous PR (#1004) failed to deploy , so this will try to fix that by deploying to [jenkins repo](https://repo.jenkins-ci.org/snapshots/) instead of Sonatype. [Sample release](https://repo.jenkins-ci.org/snapshots/fr/inria/repairnator/repairnator-plugins/1.0-SNAPSHOT/)

### CODE REVIEW

**Comment by henry-lp** [comment]
Hi @monperrus :) , The number of plugins are 8 but travis only detect 7 , but this exact test `TestComputePlugins` passed previously on travis and also locally on my machine (checked just now) . Is this test flaky ?

I'll move on and work on the next step (add all repair tools to the plugin) anyway without being blocked by this.

**Comment by monperrus** [comment]
This test is likely flaky. I fixed it and will merge it.

**Comment by monperrus** [comment]
> I'll move on and work on the next step (add all repair tools to the plugin)

Great

**Comment by henry-lp** [comment]
Thanks @monperrus  :)

**Comment by monperrus** [comment]
thank you Henry!

**Pull request merged**
