### PR TITLE
feat: SoraldBit runs directly from the realtime module

### PR DESCRIPTION
**Pull request by khaes-kth**
This adds a new mode to run the pipeline directly from the realtime-module, without using the docker image.

The pipeline and SoraldBot inside it have been adapted to work smoothly with this new mode.

### CODE REVIEW

**Comment by monperrus** [comment]
@khaes-kth some conflicts here. could we get green CI and merge?

**Comment by khaes-kth** [comment]
@monperrus 
Sure, I'll make it ready for merge next week (let's submit LighteR first)

**Comment by khaes-kth** [comment]
@monperrus : I think this is ready for review.

**Comment by monperrus** [comment]
Thanks a lot for the changes after our discussion @khaes-kth 

Methods fetchAndProcessCommitsPeriodically and processSelectedCommits should be instance methods (and not static).

**Comment by khaes-kth** [comment]
> Methods fetchAndProcessCommitsPeriodically and processSelectedCommits should be instance methods (and not static).

Fixed.

**Comment by monperrus** [comment]
Thanks a lot @khaes-kth

**Pull request merged**
