### PR TITLE
refactor: move docker test cases to other repository

### LINKED ISSUE #1057: Continuous integration pipeline is flaky
As you all know, we have long-standing problems with the Repairnator CI:
- it's too slow
- it's flaky

Having look at the build time without tests (only dependencies & compile), the Docker pull jobs take ages.

So I propose to move all tests requiring docker to a separate repo for integration testing, it could be:
- a Travis job: https://github.com/repairnator/repairnator-integration-tests
- a Jenkins job: https://ci.eclipse.org/repairnator/job/repairnator-integration-test

WDYT?

### PR DESCRIPTION
**Pull request by henry-lp**
Close #1057

### CODE REVIEW

**Comment by monperrus** [comment]
Good start, could you also move the `docker pull` from travis-before.sh and the tests that depend on them?

**Comment by henry-lp** [comment]
yes, I'll also move the testcases failed related to these docker pull.

**Comment by monperrus** [comment]
we may need to move TestSequencerRepair also.

**Comment by henry-lp** [comment]
> 
> 
> we may need to move TestSequencerRepair also.

Yes, I am waiting for CI to fail to pin-point these test cases.

**Comment by monperrus** [comment]
neat!

**Comment by henry-lp** [comment]
@monperrus  ready for review. We went down from about 44 to 30 min in the test stage :) .

**Comment by monperrus** [comment]
Thanks a lot Henry!

**Pull request merged**
