### PR TITLE
update pom of maven-repair

### LINKED ISSUE #1224: have a clean Non-snapshot version of maven-repair

### PR DESCRIPTION
**Pull request by monperrus**
fix #1224

remove old repositories, add info for releasing on central

### CODE REVIEW

**Comment by monperrus** [comment]
last one needed is exceptionparser

**Comment by monperrus** [comment]
exceptionparser comes from https://github.com/Spirals-Team/exception-parser, which is small and inactive, we proceed with moving the code see https://github.com/eclipse/repairnator/pull/1216

**Comment by monperrus** [comment]
@andre15silva repairnator-root is missing, see https://ci.eclipse.org/repairnator/job/repairnator-ci/job/PR-1201/7/console

Could you also release repairnator-root 3.4? Thanks

**Comment by andre15silva** [comment]
> Could you also release repairnator-root 3.4? Thanks

Done @monperrus, available when central syncs.

**Comment by monperrus** [comment]
Thanks, restarted the build.

**Comment by monperrus** [comment]
superseded by #1233

**Pull request closed without merging**
