### PR TITLE
[WIP]: Jenkins plugin email patches

### PR DESCRIPTION
**Pull request by henry-lp**
This address issue (#1041) 

@monperrus  this feature can be tried at [link](http://jenkins.kth-assert.net/job/repairnator%20plugin%20demo/) :)

### CODE REVIEW

**Comment by monperrus** [comment]
Great to see progress here. Thanks henry!

Jenkins has its own configuration to send emails, used for example to send emails upon build failures.

This means that we can save the user from putting all the difficult and potentially sensitive SMTP info by using this service instead.

WDYT?

**Comment by henry-lp** [comment]
hi @monperrus ,

Perhaps you mean [this feature](https://www.360logica.com/blog/email-notification-in-jenkins/), I read around and apparently you still need to provide all of those credentials there. 

There are also some problems using Jenkins email notifications, we use tmp folder to generate of stuffs so the folder name will not be fixed each time therefore one of the possibility is to set an enviroment variable for the email notification plugin to parse it after repairnator is done. Another is that the user provide a folder for repairnator to use , but then the problem is that that folder need to have enough priviledges which is not very handy either. All of this comes with an obvious price that we now have to depends on another plugin.

By far I don't see this solution being easier or more handy than providing those information directly into Repairnator, you only need to set up a fake account for repairnator to use. WDYT :) ?

**Comment by monperrus** [comment]
I mean the buil-in support (https://stackoverflow.com/a/11896118): in all serious Jenkins instances,
there is already a configured SMTP server.

**Comment by henry-lp** [comment]
new PR (#1056)

**Pull request closed without merging**
