### PR TITLE
fix: save patch on disk for NPERepair and AssertFixer

### LINKED ISSUE #1194: Add buggy file path to NPERepair Patches
When a `RepairPatch` is created in NPERepair we don't pass the buggy source file path. 
This information can be obtained from the `decisions` element in the json returned from `npefix` or from the generated `diff`.

For ODS support, we need this to happen.

https://github.com/eclipse/repairnator/blob/b17fad96c29db5960b5e9d5b5c0ea91857b167f0/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractNPERepairStep.java#L163

### PR DESCRIPTION
**Pull request by andre15silva**
Closes #1194 

## Changelog:
- Fixes buggy file path in NPERepair's and AssertFixer's RepairPatches
- Add assertions in repair step tests

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks. CI failing?

**Comment by andre15silva** [comment]
I think it's due to a flaky test. I didn't change anything to affect that test.

**Comment by andre15silva** [comment]
Ready now. It is a flaky test indeed.

**Comment by monperrus** [comment]
very nice, thanks @andre15silva

**Pull request merged**
