### PR TITLE
Feat: add initial version of github app

### PR DESCRIPTION
**Pull request by jianguda**
Signed-off-by: Jian GU <ycaxgjd@gmail.com>

### CODE REVIEW

**Comment by jianguda** [comment]
#978

**Comment by monperrus** [comment]
Cool, thanks Jian!

First comments:

* Remove: .env.example  .gitignore CODE_OF_CONDUCT.md  CONTRIBUTING.md  LICENSE
* README.md  -> move to <Root>/docs/github-app.md with the same structure as the Jenkins plugin documentation

**Comment by jianguda** [comment]
> Cool, thanks Jian!
> 
> First comments:
> 
> * Remove: .env.example  .gitignore CODE_OF_CONDUCT.md  CONTRIBUTING.md  LICENSE
> * README.md  -> move to /docs/github-app.md with the same structure as the Jenkins plugin documentation

Done

**Comment by monperrus** [comment]
Great progress!

Some questions:

Webhook URL 
* Is that mandatory to set? If not, what's the default value?
* What does https://smee.io do?

On https://github.com/apps/repairnator-bot:
* Could you add my Github profile as developer/admin?
* Could you change the website URL to https://github.com/jianguda/repairnator-bot?

We will also discuss on where to host the app and where to host the ActiveMQ.

**Comment by henry-lp** [comment]
conflict resolved :)

**Comment by jianguda** [comment]
> Webhook URL
> 
> * Is that mandatory to set? If not, what's the default value?
> * What does https://smee.io do?

Webhook URL is mandatory, so that the NodeJS server can listen to events (such as reopen PR, etc). `smee.io` helps forward these events info to our locally running NodeJS server. If the NodeJS server is running on hosting sites, like https://glitch.com, then we can directly use the assigned URL to replace current smee.io Webhook URL.

> On https://github.com/apps/repairnator-bot:
> 
> * Could you add my Github profile as developer/admin?
> * Could you change the website URL to https://github.com/jianguda/repairnator-bot?

It seems imappliable to add developer or admin. I have applied to transfer its ownership.
I have Changed to website URL.

> We will also discuss on where to host the app and where to host the ActiveMQ.

Sure. (same machine?)

**Comment by monperrus** [comment]
> Webhook URL is mandatory

Also for installation through the app server we host?

**Comment by jianguda** [comment]
> Webhook URL is mandatory
> Also for installation through the app server we host?

For Webhook URL, Yes. But `smee.io` is not mandatory.

**Comment by jianguda** [comment]
Hey Martin, I have successfully tested the NodeJS server and activeMQ.

Here is one demo:

Event: BuildID for [this rebuild of this reopen PR](https://github.com/jianguda/repairnator-bot-test/pull/2#issuecomment-579790285) is `643411969`.

ActiveMQ: We can check MQ by visiting `http://{ip}:8161/admin/` (replace {ip} with the real ip) and both username and password are the default value `admin`. Then click `Queues` in the breadcrumbs, then click `pipeline` and then click the latest message, you will see corresponding buildID at the `Message Details`.

By the way, I can not remove the `smee.io` proxy because the Webhook URL only supports URL, not IP.

**Comment by jianguda** [comment]
To reproduce the demo, please check the README file inside the repairnator's home folder.

**Comment by monperrus** [comment]
Thanks a lot Jian!

**Pull request merged**
