### PR TITLE
feat: log parser for fault detection

### PR DESCRIPTION
**Pull request by javierron**
A first effort to create a log parser. The result will be used to locate potentially fixable points.

I will continue to examine the logs produced by the first run of the Repairnator machine to identify more error types and add/remove the relevant regexes.

described in #1091 

Signed-off-by: Javier Ron <javierron90@gmail.com>

### CODE REVIEW

**Comment by monperrus** [comment]
Nice.

The changes in DockerPipelineRunner.java, RunnablePipelineContainer.java and SequencerRepair.java can be put in separate refactoring PRs. WDYT?

**Comment by javierron** [comment]
Moved the refactored files to #1093, will rebase this PR after merge. :+1:

**Comment by javierron** [comment]
@monperrus Are we looking for other types of errors beside compilation/syntax errors on the failing builds logs? I mean, there are plenty of other types but they don't seem fixable by Sequencer: e.g. pom errors, missing dependencies, invalid target release, etc.

**Comment by monperrus** [comment]
> Are we looking for other types of errors beside compilation/syntax errors on the failing builds logs?

Possibly, if they are appropriate for our setup.

> pom errors

appropriate, see also https://arxiv.org/abs/1911.01205

> missing dependencies

I'd say not appropriate for machine learning, but I would love to have missing automated repair of missing dependencies in Repairnator, see #1094 

> invalid target release

what's this error exactly?

**Comment by javierron** [comment]
> what's this error exactly?

There are many projects that use java 9+, so they throw errors like: 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project topjava: Fatal error compiling: invalid target release: 14 -> [Help 1]
```

Regarding the rest of the errros, I understand that most of them (if not all) can be are useful with the right approach and tool, but my question was more focused to SequencerRepair, until now I still have not found another kind of error (apart from complitation errors) that provide a clear file/line point of failure, e.g:

```
[ERROR] COMPILATION ERROR : 
[ERROR] /root/workspace/hemilpanchiwala/SBSCL/src/main/java/org/simulator/math/odes/MultiTable.java:[785,5] not a statement
```

**Comment by monperrus** [comment]
> There are many projects that use java 9+, so they throw errors like:

OK, created #1095 for discussing this topic. Seems to be out of our summer focus with AlphaRepairnator. 

> I still have not found another kind of error (apart from compilation errors) 

Compilation errors are in the scope of Repairnator (we have #870 and @yangzhou6666 is working on it). I'd say that they are in the scope of AlphaRepairnator and within reach with small modifs of the Sequencer code base, WDYT?

**Comment by javierron** [comment]
>  I'd say that they are in the scope of AlphaRepairnator and within reach with small modifs of the Sequencer code base, WDYT?

I would say that the latest models created by Sequencer can already attempt these fixes, however, to attempt them from Repairnator, I am creating a specific pipeline.

**Comment by monperrus** [comment]
> I am creating a specific pipeline.

ack, looking forward to it

**Comment by javierron** [comment]
@monperrus I went with the idea of a branching pipeline WDYT?

**Comment by monperrus** [comment]
BranchingStep is neat! We'll soon have a fully-fledged workflow system under AbstractStep... or we may decide to reuse an existing one.

**Comment by monperrus** [comment]
Thanks Javier!

**Pull request merged**
