### PR TITLE
`flacocobot` support for fault-localization in Repairnator

### PR DESCRIPTION
**Pull request by andre15silva**
Adds support for running `flacocobot` on PRs and as a runnable

### CODE REVIEW

**Comment by dginelli** [comment]
> @dginelli I don't remember if I've told you this, but please keep in mind that the personal access token you use must have the **public_repo** scope to be able to create pull request reviews.
> 
> It's really easy to forget that it is the case, and the error message is really unclear.
> 
> See: https://github.community/t/404-while-creating-new-pr-review/196660

Thank you for the information!

**Comment by dginelli** [comment]
> @dginelli You should now be able to run `flacocobot`.
> 
> This comment, [repairnator/failingProject#7 (review)](https://github.com/repairnator/failingProject/pull/7#pullrequestreview-795589126), was generated through the `FlacocoScanner`.
> 
> Let me know if you need help or have any doubt.

Hi @andre15silva,

Thank you for the work, I managed to run flacocobot and to push its suggestions on a pull request, but I have a couple of doubts about its functioning.

The first one is related to the volumes: I had to change [this part of the source](https://github.com/andre15silva/repairnator/blob/b0470668a6d79bc343f810da4a73db04aa718b6f/src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java#L151-L152) code adding these lines 

```
final Volume repairnatorWorkspace = Volume.builder()
        .name("repairnator_workspace")
        .driver("local")
        .build();
final Volume repairnatorWorkspaceCreated = docker.createVolume(repairnatorWorkspace);

final Volume repairnatorLogs = Volume.builder()
        .name("repairnator_logs")
        .driver("local")
        .build();
final Volume repairnatorLogsCreated = docker.createVolume(repairnatorLogs);
```
before the ones that I linked above in order to create the volumes, otherwise the pipeline was not able to run since it was not able to find the volumes. I don’t know if it is a problem that occurs only to me or not (I tried it on my Mac and on a clean virtual machine with Ubuntu 18.04).

The second aspect is related to the projects that have more than one failed open pull requests. When such a situation occurs, I noticed that the pipeline crashes. I think this is related to the fact that the pipeline tries to work on the same folder (since the repository is the same), and it fails to clone the repository.

Attached to this comment, you can find an example of the stack trace that I get when two pull requests for the same repository are available.

Also in this case, I don’t know if you already tried this test case without having errors or I’m doing anything wrong. If you have the error too, maybe a possible solution would to clone a repository in a folder that has the name of the repository followed by the id of the commit associated with the pull request, so that the folders have always unique names.

[exception.txt](https://github.com/eclipse/repairnator/files/7476683/exception.txt)

Thank you!

**Comment by dginelli** [comment]
> Oh, I created the volumes manually when I ran it. I forgot to tell you, sorry.
> 

No problem, don't worry! ;-) I didn't push the changes to create the volumes on the repo, but I can add them if you think that it is a good idea.

> I didn't try it with project with more than 1 failing PR.
> 
> I'll fix that in a moment, to have a unique directory name everytime we clone.

Ok, great! :-) Meanwhile, I continue to test the scanner with other possible cases that come to my mind.

**Comment by andre15silva** [comment]
@dginelli Conflict fixed!

I've updated the docker image too. The code should pull the new image automatically, otherwise just pull it again: `docker pull repairnator/pipeline:3.4`

Anything else let me know :)

**Comment by dginelli** [comment]
> @dginelli Conflict fixed!
> 
> I've updated the docker image too. The code should pull the new image automatically, otherwise just pull it again: `docker pull repairnator/pipeline:3.4`
> 
> Anything else let me know :)

Hi @andre15silva! Great, I can confirm you that now it works! Thank you! :-) 

In some cases, I noticed that a NullPointerException is thrown, but it does not make the program crash because there is the catch. I don’t know if it is enough to add a check before the [operation that makes the program throw the exception](https://github.com/andre15silva/repairnator/blob/b0470668a6d79bc343f810da4a73db04aa718b6f/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushFaultLocalizationSuggestions.java#L160) or if it requires more changes in other parts of the program. If I remember correctly, the exception was thrown when the pipeline was considering a pull request for which it was not possible to find any location to suggest because they were not in the diff. If I will be able to reproduce the error again, I will send you a message.

Attached to this comment, you can find the stack trace of the exception.

[exception.txt](https://github.com/eclipse/repairnator/files/7488129/exception.txt)

**Comment by dginelli** [comment]
Hi @andre15silva, I managed to reproduce the NullPointerException that occurred when I was running flacocobot on a pull request in which I had added only a new .txt file. The diff that was trying to analyze was [this one](https://patch-diff.githubusercontent.com/raw/dginelli/failingProject/pull/4.diff).

Based on some tests that I did, it seems that it works, and it does not generate any side effects. However, since I didn't write the logic of the method [computeDiffMapping(URL)](https://github.com/andre15silva/repairnator/blob/a58c6ddf859ede7676daf0963d6e2decfd7774e7/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushFaultLocalizationSuggestions.java#L131), I think it is better if you check what I did.

Moreover, I changed [the logic to set the final status associated with the PushFaultLocalizationSuggestions step](https://github.com/andre15silva/repairnator/blob/a58c6ddf859ede7676daf0963d6e2decfd7774e7/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushFaultLocalizationSuggestions.java#L44-L48). Basically, I set that the status is "SUCCESS" only if flacococo pushes its suggestions, otherwise it is "SKIPPED".

**Comment by andre15silva** [comment]
> Hi @andre15silva 

Hi @dginelli :)

> I managed to reproduce the NullPointerException that occurred when I was running flacocobot on a pull request in which I had added only a new .txt file. The diff that was trying to analyze was [this one](https://patch-diff.githubusercontent.com/raw/dginelli/failingProject/pull/4.diff).

Oh I see. I didn't consider this case when building the diff mapping function.

> Based on some tests that I did, it seems that it works, and it does not generate any side effects. However, since I didn't write the logic of the method [computeDiffMapping(URL)](https://github.com/andre15silva/repairnator/blob/a58c6ddf859ede7676daf0963d6e2decfd7774e7/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushFaultLocalizationSuggestions.java#L131), I think it is better if you check what I did.

I will check later today yes!

> Moreover, I changed [the logic to set the final status associated with the PushFaultLocalizationSuggestions step](https://github.com/andre15silva/repairnator/blob/a58c6ddf859ede7676daf0963d6e2decfd7774e7/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushFaultLocalizationSuggestions.java#L44-L48). Basically, I set that the status is "SUCCESS" only if flacococo pushes its suggestions, otherwise it is "SKIPPED".

Good idea!

Once I have gone over the change to the diff mapping function I will build and push the new pipeline image to DockerHub.

**Comment by andre15silva** [comment]
Docker image updated!

**Comment by dginelli** [comment]
Perfect, thank you! :-)

**Comment by monperrus** [comment]
per our discussion today:

* [ ] tests to be updated
* [ ] alignment with the docker image to be done
* [ ] update documentation

**Comment by andre15silva** [comment]
Updated the docker container to include https://github.com/SpoonLabs/flacoco/pull/144

**Comment by dginelli** [comment]
Hi @andre15silva,

I finished the implementation part and I updated the documentation related to the use of Flacocobot. I also added a couple of test cases to test the GithubPullRequestScanner, that is the scanner used by Flacocobot to detect the pull requests associated with the projects under analysis.

When you have time, you can check if everything is ok :-)

**Comment by monperrus** [comment]
Great, thanks Davide! @andre15silva <https://github.com/andre15silva> WDYT?

**Comment by andre15silva** [comment]
> Great, thanks Davide! @andre15silva <[@andre15silva](https://github.com/andre15silva)> WDYT?

Oh my, this thread got buried sorry @dginelli !

I'm busy until Friday, but as soon as I'm done I'll go over the changes and finish what's left (tests and docker at least).

**Comment by andre15silva** [comment]
- [ ] tests to be updated
- [ ] alignment with the docker image to be done

**Comment by andre15silva** [comment]
Ready for review @monperrus , the remaining tasks needs to be done after we merge this (#1248)

**Pull request merged**
