### PR TITLE
Fix: SequencerRepair: wait for patch to apply before validating it.

### PR DESCRIPTION
**Pull request by javierron**
Signed-off-by: Javier Ron <javierron90@gmail.com>

### CODE REVIEW

**Comment by monperrus** [comment]
LGTM. CI failing?

**Comment by andre15silva** [comment]
CI is failing because Sorald's version that is compatible with Java 8 is no longer available in the repository. Same issue as in #1172.

**Comment by monperrus** [comment]
We have a chicken and egg problem. Trying to fix with https://github.com/eclipse/repairnator/pull/1192

**Comment by monperrus** [comment]
Merged #1192, restarted build.

**Comment by monperrus** [comment]
#1192 fixed CI, CI is green here, patch merged, thanks @javierron !

**Pull request merged**
