### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PoojaChandak**
typo/grammatical changes suggested

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks a lot @PoojaChandak your your attention to details! Could you sign the Eclipse License Agreement on their website?

**Comment by PoojaChandak** [comment]
Singed. Thanks.

**Comment by monperrus** [comment]
Thanks. Could you also sign your commit? (see message "the "Signed-off-by footer" which is required for all commits made by a contributor." on https://accounts.eclipse.org/legal/eca/validation/52311)

**Comment by PoojaChandak** [comment]
will create another with appropriate comments

**Pull request closed without merging**
