### PR TITLE
refactor: update test projects and build references

### PR DESCRIPTION
**Pull request by andre15silva**
Waiting for project moves from #1195

### CODE REVIEW

**Comment by andre15silva** [comment]
`maven.inria.fr` is down, CI failing because of that

**Comment by monperrus** [comment]
> maven.inria.fr is down, CI failing because of that

Seems up again. But I don't find a way to restart failing builds on https://ci.eclipse.org/repairnator/job/repairnator-ci/. @javierron any idea?

**Comment by javierron** [comment]
@monperrus I've restarted the failing builds on all pull requests

**Comment by javierron** [comment]
Hey @andre15silva, I want to rebase these changes into my PR #1215. What's left to do here?

**Comment by andre15silva** [comment]
I'm waiting for the projects mentioned in #1195 to be moved. When that is done, it's a matter of changing the references in the tests (maybe some builds need to be triggered again too).

**Comment by monperrus** [comment]
@andre15silva do we need to move all projects or can we proceed as is, with the ones which have already been moved?

if we can proceed, we would unwip and merge this one, and @javierron would rebase #1195 afterwards.

WDYT?

**Comment by andre15silva** [comment]
Yes, we can merge as is and leave the rest of the changes pending. 

I'll rebase this PR and mark it ready.

**Comment by monperrus** [comment]
> I'll rebase this PR and mark it ready.

perfect, and @javierron will merge it afterwards

**Comment by andre15silva** [comment]
@javierron do you know what might be causing the build failure in `repairnator-runtime`?

The first build failed with test cases returning 404 errors, and the two others timed-out.

**Comment by javierron** [comment]
I've fixed those 404s in my PR, the timeouts might be related. I will cherry-pick my commit to this branch to see if we can get the tests passing.

**Comment by andre15silva** [comment]
> I think the best solution is to create our own builds (maybe in repairnator/failingProject ?) that fulfill the tests' requirements.

I think so too. I'm doing that change and adding it to this PR.

**Comment by andre15silva** [comment]
@javierron There are two issues right now:
- I'm not being able to get `TestComputePlugins` with the new branch I created for this test in https://github.com/repairnator/failingProject/tree/plugins. It doesn't detect the plugin.
- There are two test cases in `TestCheckoutBuild` that depend on two builds I'm not being able to reproduce. 
	- The first, `testCheckoutBuildFromPRWithMissingMerge`, tests a build with merge conflicts, but Travis doesn't run the builds for those anymore as far as I understood. 
	- The second, `testCheckoutBuildFromPROtherRepo`, tries to checkout a build of a PR from another repo and fails, but the builds I've created don't fail.

WDYT we should do with these? The latter issue doesn't affect (currently) the tests, as the builds are still available. The first one needs a change tho.

**Comment by javierron** [comment]
@andre15silva I believe the plugins in the test project should be outside the `<pluginManagment>` key. I'm not 100% sure but the pom structure we are trying to recreate was [this](https://github.com/eclipse/repairnator/blob/9e8d85bf320d6b71c34bf81c967ba0b593105691/repairnator/pom.xml) one. I would have changed it right now but I don't have push access to repairnator/failingProject :upside_down_face:

**Comment by andre15silva** [comment]
> @andre15silva I believe the plugins in the test project should be outside the `<pluginManagment>` key. I'm not 100% sure but the pom structure we are trying to recreate was [this](https://github.com/eclipse/repairnator/blob/9e8d85bf320d6b71c34bf81c967ba0b593105691/repairnator/pom.xml) one. 

It was that indeed. Fixed! Thanks!

> I would have changed it right now but I don't have push access to repairnator/failingProject upside_down_face

I don't have the permission to add you, needs to be @monperrus

**Comment by javierron** [comment]
Thanks @andre15silva! We're finally green again. :rocket: 

Since this is blocking our other PRs, let's merge these changes and take care of the 2 remaining builds in a separate PR.

**Comment by monperrus** [comment]
Thanks a lot!

**Pull request merged**
