### PR TITLE
feat: fetch-mode added to GithubScanner

### PR DESCRIPTION
**Pull request by khaes-kth**
This PR makes us able to determine if we want the scanner to fetch only failed commits or all commits.

### CODE REVIEW

**Comment by khaes-kth** [comment]
@javierron 
Seems that the timeout has exceeded. What to do now?

**Comment by javierron** [comment]
It seems that we are getting rate limited on one of the tests we added. 

```error occurred for: SpoonLabs/sorald
org.kohsuke.github.GHException: Failed to retrieve https://api.github.com/repos/SpoonLabs/sorald/commits/1a7346131473a573ae4e35021a747dad3f98afbb/check-runs
...
Caused by: org.kohsuke.github.HttpException: Rate limit violation
```

Most likely we will have to provide a token.

**Comment by javierron** [comment]
Thanks @khaes-kth, great addition to the scanner! :rocket: :rocket:

**Comment by khaes-kth** [comment]
Finally!

We have two more PRs to merge :)

Thanks,

**Pull request merged**
